#!/usr/bin/env sh

yabai -m config layout bsp
yabai -m config external_bar all:50:0
yabai -m config window_gap 12
yabai -m config top_padding    12
yabai -m config bottom_padding 12
yabai -m config left_padding   12
yabai -m config right_padding  12

yabai -m signal --add event=window_created   action="$HOME/.config/yabai/auto_padding.sh"
yabai -m signal --add event=window_destroyed action="$HOME/.config/yabai/auto_padding.sh"
yabai -m signal --add event=space_changed    action="$HOME/.config/yabai/auto_padding.sh"

$HOME/.config/yabai/auto_padding.sh
