#!/bin/bash

FONT="Share Tech Mono"
FONT_SIZE="13.0"
PLUGIN_DIR="$HOME/.config/sketchybar/plugins"

FREQ_CLOCK=10
FREQ_WEATHER=1800
FREQ_MAIL=60
FREQ_CPU=5
FREQ_BATTERY=60
FREQ_WIFI=30
FREQ_CALENDAR=60
FREQ_NOWPLAYING=5

if [[ "$(defaults read -g AppleInterfaceStyle 2>/dev/null)" == "Dark" ]]; then
  BAR_COLOR=0xff1c1c1e
  LABEL_COLOR=0xffffffff
  ICON_COLOR=0xff6B9FFF
  HIGHLIGHT_COLOR=0xff6ECD6B
  SECONDARY_COLOR=0xff8e8e93
else
  BAR_COLOR=0xffffffff
  LABEL_COLOR=0xff000000
  ICON_COLOR=0xff3B7FE8
  HIGHLIGHT_COLOR=0xff3EA83B
  SECONDARY_COLOR=0xff6e6e73
fi

COLOR_RED=0xffFF5555
COLOR_ORANGE=0xffFF9838
COLOR_YELLOW=0xffFFD02A
COLOR_GREEN=0xff6ECD6B
COLOR_TEAL=0xff5EE0D4
COLOR_BLUE=0xff6B9FFF
COLOR_PURPLE=0xffBB66DD
COLOR_PINK=0xffFF4488
COLOR_WHITE=0xffffffff
COLOR_GREY=0xff8e8e93

export FONT FONT_SIZE PLUGIN_DIR
export BAR_COLOR LABEL_COLOR ICON_COLOR HIGHLIGHT_COLOR SECONDARY_COLOR
export COLOR_RED COLOR_ORANGE COLOR_YELLOW COLOR_GREEN COLOR_TEAL COLOR_BLUE COLOR_PURPLE COLOR_PINK COLOR_WHITE COLOR_GREY
export FREQ_CLOCK FREQ_WEATHER FREQ_MAIL FREQ_CPU FREQ_BATTERY FREQ_WIFI FREQ_CALENDAR FREQ_NOWPLAYING
